version: "3"

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ".:/app:rw"
      - "./data:/data:rw"
      - "node_modules:/app/node_modules"
    command: npm run dev -- --host 0.0.0.0 --port 80

volumes:
  node_modules:
